name: Itsmyunderscore
version: '${version}'
main: me.itsmyunderscore.Itsmyunderscore
api-version: 1.17
authors: [ ItsMYunderscore ]
description: Command control plugin
commands:
  whoisgay:
    description: Responds with who the gay is
